source 'http://rubygems.org'

gem 'rails', "~> 3.1.4"

# For development
gem 'omega', :path => "../../omega"
gem 'accepts-flattened-values', :path => '../../accepts-flattened-values'

# For production
#gem 'omega', :git => "https://pmiller10@github.com/sapresearch/omega.git"
#gem 'accepts-flattened-values', :git => 'https://pmiller10@github.com/pmiller10/accepts-flattened-values.git'

platforms :jruby do
	gem 'activerecord-jdbcmysql-adapter'
	gem 'activerecord-jdbc-adapter'
	gem 'jruby-openssl'
end

platforms :ruby do
	gem 'mysql2', "0.3.10"
end

gem 'jquery-rails'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  #gem 'sass-rails',   "~> 3.2.0"
  #gem 'coffee-rails', "~> 3.2.0"
  gem 'uglifier'
end

# Bundle the extra gems:
# gem 'aws-s3', :require => 'aws/s3'
