source 'http://rubygems.org'

gem 'rails', "~> 3.2.2"

gem 'omega', :path => "../../omega"

platforms :jruby do
	gem 'activerecord-jdbcmysql-adapter'
	gem 'activerecord-jdbc-adapter'
	gem 'jruby-openssl'
end

gem 'jquery-rails'
gem 'accepts-flattened-values', :path => '../../accepts-flattened-values'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  #gem 'sass-rails',   "~> 3.2.0"
  #gem 'coffee-rails', "~> 3.2.0"
  gem 'uglifier'
end

# Bundle the extra gems:
# gem 'aws-s3', :require => 'aws/s3'
